### ISSUE TITLE
Answer class

### ISSUE THREAD

**Issue by ShaharMorad** [seannaor/EntityTests#15]
I think we should merg the textualAnswer and numeralAnswer into just one field of type JSON.
That way we can easly support different types of questions.

**Comment by seannaor** [comment]
אני חושב שאחיה רצה בכוונה שזה יהיה בשדות כדי שיהיה יותר קל לתת סטטיסטיקה על התשובות של הנסיינים.. כי אם זה בגייסון זה יהיה בעייתי לעשות את זה

**Comment by ShaharMorad** [comment]
המימוש עכשיו תומך רק בתשובות לשאלה פתוחה או תשובה מספרית יחידה.
לדעתי שדה שמכיל ממש את התשובה/תשובות צריך להיות ג'ייסון או משהו בסגנון, 
גם מבחינת המימוש של השאלה עצמה (ג'ייסון) וגם כדי להימנע ממימוש מכוער של שאר סוגי התשובות
